export const ADMIN_USER_CREATE_REQUEST = 'ADMIN_USER_CREATE_REQUEST'
export const ADMIN_USER_CREATE_SUCCESS = 'ADMIN_USER_CREATE_SUCCESS'
export const ADMIN_USER_CREATE_FAIL = 'ADMIN_USER_CREATE_FAIL'
export const ADMIN_USER_CREATE_RESET = 'ADMIN_USER_CREATE_RESET'

export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST'
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS'
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL'
export const ADMIN_USER_LIST_RESET = 'ADMIN_USER_LIST_RESET'