export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST'
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS'
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL'
export const CUSTOMER_DETAILS_RESET = 'CUSTOMER_DETAILS_RESET'

export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL'
export const CUSTOMER_LIST_RESET = 'CUSTOMER_LIST_RESET'

export const CUSTOMER_INVOICES_REQUEST = 'CUSTOMER_INVOICES_REQUEST'
export const CUSTOMER_INVOICES_SUCCESS = 'CUSTOMER_INVOICES_SUCCESS'
export const CUSTOMER_INVOICES_FAIL = 'CUSTOMER_INVOICES_FAIL'
export const CUSTOMER_INVOICES_RESET = 'CUSTOMER_INVOICES_RESET'

export const CUSTOMER_APP_ORDERS_REQUEST = 'CUSTOMER_APP_ORDERS_REQUEST'
export const CUSTOMER_APP_ORDERS_SUCCESS = 'CUSTOMER_APP_ORDERS_SUCCESS'
export const CUSTOMER_APP_ORDERS_FAIL = 'CUSTOMER_APP_ORDERS_FAIL'
export const CUSTOMER_APP_ORDERS_RESET = 'CUSTOMER_APP_ORDERS_RESET'

export const CUSTOMER_SALES_ORDERS_REQUEST = 'CUSTOMER_SALES_ORDERS_REQUEST'
export const CUSTOMER_SALES_ORDERS_SUCCESS = 'CUSTOMER_SALES_ORDERS_SUCCESS'
export const CUSTOMER_SALES_ORDERS_FAIL = 'CUSTOMER_SALES_ORDERS_FAIL'

export const CUSTOMER_NOTES_REQUEST = 'CUSTOMER_NOTES_REQUEST'
export const CUSTOMER_NOTES_SUCCESS = 'CUSTOMER_NOTES_SUCCESS'
export const CUSTOMER_NOTES_FAIL = 'CUSTOMER_NOTES_FAIL'
export const CUSTOMER_NOTES_RESET = 'CUSTOMER_NOTES_RESET'

export const CUSTOMER_SALES_LIST_REQUEST = 'CUSTOMER_SALES_LIST_REQUEST'
export const CUSTOMER_SALES_LIST_SUCCESS = 'CUSTOMER_SALES_LIST_SUCCESS'
export const CUSTOMER_SALES_LIST_FAIL = 'CUSTOMER_SALES_LIST_FAIL'
export const CUSTOMER_SALES_LIST_RESET = 'CUSTOMER_SALES_LIST_RESET'