export const ENVIRONMENT_VAR_REQUEST = 'ENVIRONMENT_VAR_REQUEST'
export const ENVIRONMENT_VAR_SUCCESS = 'ENVIRONMENT_VAR_SUCCESS'
export const ENVIRONMENT_VAR_FAIL = 'ENVIRONMENT_VAR_FAIL'
export const ENVIRONMENT_VAR_RESET = 'ENVIRONMENT_VAR_RESET'